apiVersion: v1
kind: ServiceAccount
metadata:
  name: crd-wizard-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crd-wizard-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
  # "Extensive" permissions requested. 
  # This provides full access to all resources in all API groups.
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crd-wizard-binding
subjects:
- kind: ServiceAccount
  name: crd-wizard-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: crd-wizard-role
  apiGroup: rbac.authorization.k8s.io
