apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crd-wizard
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: crd-wizard
subjects:
  - kind: ServiceAccount
    name: crd-wizard
    namespace: crd-wizard
