apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: crd-wizard

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - deployment.yaml
  - service.yaml

labels:
  - pairs:
      app.kubernetes.io/name: crd-wizard
      app.kubernetes.io/component: web

images:
  - name: ghcr.io/pehlicd/crd-wizard
    newTag: latest
